### ISSUE TITLE
Authorization Fails in Sitecore 9.1.1

### ISSUE THREAD

**Issue by bewards** [alphasolutionsrepo/pipeline.debug#1]
The `PipelineDebugController` attribute `AdministratorOnly` checks for `Sitecore.Context.IsAdministrator` that always fails on my instance of Sitecore 9.1.1.

![image](https://user-images.githubusercontent.com/3927169/72365566-76a26480-36c6-11ea-84d0-1a7cd1386014.png)

In 9.1, you either have to patch in the path of your custom admin pages/routes to the list of the siteNeutralPaths for the ValidateSiteNeutralPaths processor in the owin.cookieAuthentication.validateIdentity pipeline **or** append `sc_site=[site]` to the API calls.

I fixed this locally by patching in the following:

```
        <processor type="Sitecore.Owin.Authentication.Pipelines.CookieAuthentication.ValidateIdentity.ValidateSiteNeutralPaths, Sitecore.Owin.Authentication">
          <siteNeutralPaths hint="list">
            <path>/pipelinedebug/pipelinedetails</path>
            <path>/pipelinedebug/addprocessor</path>
            <path>/pipelinedebug/moveprocessor</path>
            <path>/pipelinedebug/getdebugprocessors</path>
            <path>/pipelinedebug/removeprocessor</path>
            <path>/pipelinedebug/getdiscoveryroots</path>
            <path>/pipelinedebug/discover</path>
            <path>/pipelinedebug/getsettings</path>
            <path>/pipelinedebug/savesettings</path>
            <path>/pipelinedebug/getoutput</path>
            <path>/pipelinedebug/exportconfiguration</path>
            <path>/pipelinedebug/importconfiguration</path>
            <path>/pipelinedebug/saveprocessortaxonomies</path>
            <path>/pipelinedebug/listpipelines</path>
            <path>/pipelinedebug/login</path>
            <path>/pipelinedebug/logout</path>
          </siteNeutralPaths>
        </processor>
```

**Comment by mortenengel** [comment]
Hi bewards,

Thanks for bringing this to my attention - and an easily implemented solution no less! I've had a busy year and haven't had the time to revisit/test this, but I will add this to the repo and the package ASAP.

Kind regards,
Morten

**Comment by mortenengel** [comment]
Added a general neutral path for all of /pipelinedebug/ and updated the nuget. Package has been uploaded to marketplace but is pending.
Closing the issue.
